//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteConsola.ServicioReniecFake {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioReniecFake.ReniecServiceSoap")]
    public interface ReniecServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarCiudadanoDni", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListarCiudadanoDni(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarCiudadanoDni", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarCiudadanoDniAsync(string dni);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReniecServiceSoapChannel : ClienteConsola.ServicioReniecFake.ReniecServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReniecServiceSoapClient : System.ServiceModel.ClientBase<ClienteConsola.ServicioReniecFake.ReniecServiceSoap>, ClienteConsola.ServicioReniecFake.ReniecServiceSoap {
        
        public ReniecServiceSoapClient() {
        }
        
        public ReniecServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReniecServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReniecServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReniecServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ListarCiudadanoDni(string dni) {
            return base.Channel.ListarCiudadanoDni(dni);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarCiudadanoDniAsync(string dni) {
            return base.Channel.ListarCiudadanoDniAsync(dni);
        }
    }
}
